version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - sudo npm i -g serverless
      - cd functions
      - npm i
      - sls deploy --stage staging
  post_build:
    commands:
      - echo Build completed on `date`