version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - sudo npm i -g serverless

      - cd services/APIService
      - npm i
      - sls deploy --stage ${Stage}

      - cd ../SocketsService
      - npm i
      - sls deploy --stage ${Stage}

      - cd ../VotingService
      - npm i
      - sls deploy --stage ${Stage}
      
      - cd ../TeamsService
      - npm i
      - sls deploy --stage ${Stage}
  post_build:
    commands:
      - echo Build completed on `date`